### ISSUE TITLE
Breaks with newest google.golang.org/appengine

### ISSUE THREAD

**Issue by jfinnson** [CaptainCodeman/datastore-mapper#28]
Interaction with google.golang.org/appengine/datastore breaks with its newest version.
Error may reside within datastore-locker. But unlikely.

Running example1 causes no output or error message.

Logging the error output from Schedule in task.go (datastore-locker) will output:
'datastore: multiple Properties with Name "active", but Multiple is false'. 
The property name changes each time to a property of common.

Not sure of the root cause (or change from google.golang.org/appengine/datastore) but it is possibly due to merging the entity and common properties. (job.go line 118)

In addition to updating the code to conform to the newest version of google.golang.org/appengine/datastore. I would recommend handling errors from datastore-locker/task.go (Schedule function specifically) within the startJobHandler function (job_spec.go, line 173).

**Comment by CaptainCodeman** [comment]
Thanks, looks like that datastore change is breaking and could have a huge impact for some apps (!)

This should fix it and I've improved the messaging so any errors aren't swallowed.

It's a little counter intuitive how the common properties have to be set to ignored in order to save correctly so I'll look at refactoring how that works when I get chance.
